from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_elementWindow(object):
    def __init__(self,getElementName,getAtomicSymbol,getAtomicNumber,\
        getAtomicWeight,getDensity,getMeltingPoint,getBoilingPoint,\
            getOxidationState,getElectronegativity,getPeriod,\
                getGroupNumber,getGroup,getElementGroup,\
                    getElectronConfiguration):
        super().__init__()
        self.elementName = getElementName
        self.atomicSymbol = getAtomicSymbol
        self.atomicNumber = getAtomicNumber
        self.atomicWeight = getAtomicWeight
        self.density = getDensity
        self.meltingPointKelvin = getMeltingPoint
        self.boilingPointKelvin = getBoilingPoint
        self.oxidationState = getOxidationState
        self.electronegativity = getElectronegativity
        self.period = getPeriod
        self.groupNumber = getGroupNumber
        self.group = getGroup
        self.elementGroup = getElementGroup
        self.electronConfiguration = getElectronConfiguration

    def setupUi(self, elementWindow):                                   # This will be used as a template
        elementWindow.setObjectName("elementWindow")                    # in generating a window with all
        elementWindow.resize(325, 375)                                  # of the element information
        elementWindow.setMinimumSize(QtCore.QSize(325, 375))            # that this class will receive
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        elementWindow.setFont(font)
        elementWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/flask-6.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        elementWindow.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(elementWindow)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.upperBox = QtWidgets.QGridLayout()
        self.upperBox.setSpacing(0)
        self.upperBox.setObjectName("upperBox")
        self.label_atomicSymbolTitle = QtWidgets.QLabel(elementWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_atomicSymbolTitle.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(50)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_atomicSymbolTitle.setFont(font)
        self.label_atomicSymbolTitle.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.label_atomicSymbolTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_atomicSymbolTitle.setObjectName("label_atomicSymbolTitle")
        self.upperBox.addWidget(self.label_atomicSymbolTitle, 0, 0, 1, 1)
        self.label_elementNameTitle = QtWidgets.QLabel(elementWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(227, 108, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 108, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_elementNameTitle.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(24)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_elementNameTitle.setFont(font)
        self.label_elementNameTitle.setIndent(5)
        self.label_elementNameTitle.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.label_elementNameTitle.setObjectName("label_elementNameTitle")
        self.upperBox.addWidget(self.label_elementNameTitle, 0, 1, 1, 1)
        self.upperBox.setColumnStretch(0, 2)
        self.upperBox.setColumnStretch(1, 5)
        self.gridLayout_2.addLayout(self.upperBox, 0, 0, 1, 1)
        self.lowerBox = QtWidgets.QGridLayout()
        self.lowerBox.setObjectName("lowerBox")
        self.label_period = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_period.setFont(font)
        self.label_period.setIndent(10)
        self.label_period.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_period.setObjectName("label_period")
        self.lowerBox.addWidget(self.label_period, 6, 0, 1, 1)
        self.label_groupNumber = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_groupNumber.setFont(font)
        self.label_groupNumber.setIndent(10)
        self.label_groupNumber.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_groupNumber.setObjectName("label_groupNumber")
        self.lowerBox.addWidget(self.label_groupNumber, 7, 0, 1, 1)
        self.label_electronConfiguration = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_electronConfiguration.setFont(font)
        self.label_electronConfiguration.setIndent(10)
        self.label_electronConfiguration.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_electronConfiguration.setObjectName("label_electronConfiguration")
        self.lowerBox.addWidget(self.label_electronConfiguration, 11, 0, 1, 1)
        self.label_atomicWeight = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_atomicWeight.setFont(font)
        self.label_atomicWeight.setIndent(10)
        self.label_atomicWeight.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_atomicWeight.setObjectName("label_atomicWeight")
        self.lowerBox.addWidget(self.label_atomicWeight, 1, 0, 1, 1)
        self.label_boilingPointKelvin = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_boilingPointKelvin.setFont(font)
        self.label_boilingPointKelvin.setIndent(10)
        self.label_boilingPointKelvin.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_boilingPointKelvin.setObjectName("label_boilingPointKelvin")
        self.lowerBox.addWidget(self.label_boilingPointKelvin, 4, 0, 1, 1)
        self.label_elementGroup = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_elementGroup.setFont(font)
        self.label_elementGroup.setIndent(10)
        self.label_elementGroup.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_elementGroup.setObjectName("label_elementGroup")
        self.lowerBox.addWidget(self.label_elementGroup, 9, 0, 1, 1)
        self.label_oxidationStates = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_oxidationStates.setFont(font)
        self.label_oxidationStates.setIndent(10)
        self.label_oxidationStates.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_oxidationStates.setObjectName("label_oxidationStates")
        self.lowerBox.addWidget(self.label_oxidationStates, 5, 0, 1, 1)
        self.label_group = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_group.setFont(font)
        self.label_group.setIndent(10)
        self.label_group.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_group.setObjectName("label_group")
        self.lowerBox.addWidget(self.label_group, 8, 0, 1, 1)
        self.label_atomicNumber = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_atomicNumber.setFont(font)
        self.label_atomicNumber.setIndent(10)
        self.label_atomicNumber.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_atomicNumber.setObjectName("label_atomicNumber")
        self.lowerBox.addWidget(self.label_atomicNumber, 0, 0, 1, 1)
        self.label_electronegativity = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_electronegativity.setFont(font)
        self.label_electronegativity.setIndent(10)
        self.label_electronegativity.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_electronegativity.setObjectName("label_electronegativity")
        self.lowerBox.addWidget(self.label_electronegativity, 10, 0, 1, 1)
        self.label_density = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_density.setFont(font)
        self.label_density.setIndent(10)
        self.label_density.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_density.setObjectName("label_density")
        self.lowerBox.addWidget(self.label_density, 2, 0, 1, 1)
        self.label_meltingPointKelvin = QtWidgets.QLabel(elementWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_meltingPointKelvin.setFont(font)
        self.label_meltingPointKelvin.setIndent(10)
        self.label_meltingPointKelvin.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_meltingPointKelvin.setObjectName("label_meltingPointKelvin")
        self.lowerBox.addWidget(self.label_meltingPointKelvin, 3, 0, 1, 1)
        self.lowerBox.setColumnStretch(0, 2)
        self.gridLayout_2.addLayout(self.lowerBox, 2, 0, 1, 1)
        self.label_line = QtWidgets.QLabel(elementWindow)
        self.label_line.setMaximumSize(QtCore.QSize(16777215, 5))
        if self.elementGroup == "Non-metals":                                           # Adjust line color depending on element group
            self.label_line.setStyleSheet("background-color: rgb(255, 255, 209);")
        elif self.elementGroup == "Noble Gases":
            self.label_line.setStyleSheet("background-color: rgb(255, 228, 196);")
        elif self.elementGroup == "Alkali Metals":
            self.label_line.setStyleSheet("background-color: rgb(255, 202, 199);")
        elif self.elementGroup == "Alkaline Earth Metals":
            self.label_line.setStyleSheet("background-color: rgb(209, 211, 255);")
        elif self.elementGroup == "Metalloids":
            self.label_line.setStyleSheet("background-color: rgb(224, 240, 195);")
        elif self.elementGroup == "Halogens":
            self.label_line.setStyleSheet("background-color: rgb(255, 255, 150);")
        elif self.elementGroup == "Transition Metals":
            self.label_line.setStyleSheet("background-color: rgb(192, 220, 255);")
        elif self.elementGroup == "Post-transition Metals":
            self.label_line.setStyleSheet("background-color: rgb(203, 255, 197);")
        elif self.elementGroup == "Lanthanides":
            self.label_line.setStyleSheet("background-color: rgb(192, 255, 255);")
        elif self.elementGroup == "Actinides":
            self.label_line.setStyleSheet("background-color: rgb(197, 255, 234);")
        else:
            self.label_line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_line.setText("")
        self.label_line.setObjectName("label_line")
        self.gridLayout_2.addWidget(self.label_line, 1, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 10)
        self.gridLayout_2.setRowStretch(2, 25)

        self.retranslateUi(elementWindow)
        QtCore.QMetaObject.connectSlotsByName(elementWindow)

    def retranslateUi(self, elementWindow):                                                     # This is how the info is displayed
        _translate = QtCore.QCoreApplication.translate
        elementWindow.setWindowTitle(_translate("elementWindow", f"{self.elementName}"))
        self.label_atomicSymbolTitle.setText(_translate("elementWindow", f"{self.atomicSymbol}"))
        self.label_elementNameTitle.setText(_translate("elementWindow", f"{self.elementName}"))
        self.label_period.setText(_translate("elementWindow", f"Period: {self.period}"))
        self.label_groupNumber.setText(_translate("elementWindow", f"Group Number: {self.groupNumber}"))
        self.label_electronConfiguration.setText(_translate("elementWindow", f"Electron Configuration: {self.electronConfiguration}"))
        self.label_atomicWeight.setText(_translate("elementWindow", f"Atomic Weight: {self.atomicWeight} g/mol"))
        self.label_boilingPointKelvin.setText(_translate("elementWindow", f"Boiling Point: {self.boilingPointKelvin} Kelvin"))
        self.label_elementGroup.setText(_translate("elementWindow", f"Element Group: {self.elementGroup}"))
        self.label_oxidationStates.setText(_translate("elementWindow", f"Oxidation State/s: {self.oxidationState}"))
        self.label_group.setText(_translate("elementWindow", f"Group: {self.group}"))
        self.label_atomicNumber.setText(_translate("elementWindow", f"Atomic Number: {self.atomicNumber}"))
        self.label_electronegativity.setText(_translate("elementWindow", f"Electronegativity: {self.electronegativity}"))
        self.label_density.setText(_translate("elementWindow", f"Density: {self.density} g/cm\u00B3"))
        self.label_meltingPointKelvin.setText(_translate("elementWindow", f"Melting Point: {self.meltingPointKelvin} Kelvin"))
    import assets_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    elementWindow = QtWidgets.QWidget()
    ui = Ui_elementWindow()
    ui.setupUi(elementWindow)
    elementWindow.show()
    sys.exit(app.exec_())
