from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_howToUse(object):
    def setupUi(self, howToUse):
        howToUse.setObjectName("howToUse")
        howToUse.resize(300, 350)
        howToUse.setMinimumSize(QtCore.QSize(300, 350))
        howToUse.setMaximumSize(QtCore.QSize(300, 350))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(7)
        howToUse.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/question.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        howToUse.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(howToUse)
        self.centralwidget.setObjectName("centralwidget")
        self.label_howToUseTitle = QtWidgets.QLabel(self.centralwidget)
        self.label_howToUseTitle.setGeometry(QtCore.QRect(0, 0, 301, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(40, 210, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 210, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_howToUseTitle.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(30)
        self.label_howToUseTitle.setFont(font)
        self.label_howToUseTitle.setStyleSheet("")
        self.label_howToUseTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_howToUseTitle.setObjectName("label_howToUseTitle")
        self.groupBox_periodicTableOfElements = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_periodicTableOfElements.setGeometry(QtCore.QRect(10, 80, 281, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_periodicTableOfElements.setFont(font)
        self.groupBox_periodicTableOfElements.setFlat(False)
        self.groupBox_periodicTableOfElements.setObjectName("groupBox_periodicTableOfElements")
        self.label_bullet1 = QtWidgets.QLabel(self.groupBox_periodicTableOfElements)
        self.label_bullet1.setGeometry(QtCore.QRect(0, 20, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_bullet1.setFont(font)
        self.label_bullet1.setIndent(5)
        self.label_bullet1.setObjectName("label_bullet1")
        self.label_bullet2 = QtWidgets.QLabel(self.groupBox_periodicTableOfElements)
        self.label_bullet2.setGeometry(QtCore.QRect(0, 40, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_bullet2.setFont(font)
        self.label_bullet2.setIndent(5)
        self.label_bullet2.setObjectName("label_bullet2")
        self.label_bullet3 = QtWidgets.QLabel(self.groupBox_periodicTableOfElements)
        self.label_bullet3.setGeometry(QtCore.QRect(0, 60, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_bullet3.setFont(font)
        self.label_bullet3.setIndent(5)
        self.label_bullet3.setObjectName("label_bullet3")
        self.groupBox_chemicalEquationBalancer = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_chemicalEquationBalancer.setGeometry(QtCore.QRect(10, 170, 281, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_chemicalEquationBalancer.setFont(font)
        self.groupBox_chemicalEquationBalancer.setObjectName("groupBox_chemicalEquationBalancer")
        self.label_bullet4 = QtWidgets.QLabel(self.groupBox_chemicalEquationBalancer)
        self.label_bullet4.setGeometry(QtCore.QRect(0, 20, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_bullet4.setFont(font)
        self.label_bullet4.setIndent(5)
        self.label_bullet4.setObjectName("label_bullet4")
        self.label_bullet5 = QtWidgets.QLabel(self.groupBox_chemicalEquationBalancer)
        self.label_bullet5.setGeometry(QtCore.QRect(0, 40, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_bullet5.setFont(font)
        self.label_bullet5.setIndent(5)
        self.label_bullet5.setObjectName("label_bullet5")
        self.label_bullet6 = QtWidgets.QLabel(self.groupBox_chemicalEquationBalancer)
        self.label_bullet6.setGeometry(QtCore.QRect(0, 60, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_bullet6.setFont(font)
        self.label_bullet6.setIndent(5)
        self.label_bullet6.setObjectName("label_bullet6")
        self.groupBox_keyboardShortcut = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_keyboardShortcut.setGeometry(QtCore.QRect(10, 260, 281, 81))
        self.groupBox_keyboardShortcut.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_keyboardShortcut.setFont(font)
        self.groupBox_keyboardShortcut.setObjectName("groupBox_keyboardShortcut")
        self.label_bullet7 = QtWidgets.QLabel(self.groupBox_keyboardShortcut)
        self.label_bullet7.setGeometry(QtCore.QRect(0, 20, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_bullet7.setFont(font)
        self.label_bullet7.setIndent(5)
        self.label_bullet7.setObjectName("label_bullet7")
        self.label_bullet9 = QtWidgets.QLabel(self.groupBox_keyboardShortcut)
        self.label_bullet9.setGeometry(QtCore.QRect(0, 60, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_bullet9.setFont(font)
        self.label_bullet9.setIndent(5)
        self.label_bullet9.setObjectName("label_bullet9")
        self.label_bullet8 = QtWidgets.QLabel(self.groupBox_keyboardShortcut)
        self.label_bullet8.setGeometry(QtCore.QRect(0, 40, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_bullet8.setFont(font)
        self.label_bullet8.setIndent(5)
        self.label_bullet8.setObjectName("label_bullet8")
        howToUse.setCentralWidget(self.centralwidget)

        self.retranslateUi(howToUse)
        QtCore.QMetaObject.connectSlotsByName(howToUse)

    def retranslateUi(self, howToUse):
        _translate = QtCore.QCoreApplication.translate
        howToUse.setWindowTitle(_translate("howToUse", "How to use?"))
        self.label_howToUseTitle.setText(_translate("howToUse", "How to use?"))
        self.groupBox_periodicTableOfElements.setTitle(_translate("howToUse", "Periodic Table of Elements"))
        self.label_bullet1.setText(_translate("howToUse", "• Hover an element to quickly check for its element name."))
        self.label_bullet2.setText(_translate("howToUse", "• Click an element to see its properties."))
        self.label_bullet3.setText(_translate("howToUse", "Note: Elements are color coded for each Element Group."))
        self.groupBox_chemicalEquationBalancer.setTitle(_translate("howToUse", "Chemical Equation Balancer"))
        self.label_bullet4.setText(_translate("howToUse", "• Enclose the element in braces \'[ ]\' and its number beside."))
        self.label_bullet5.setText(_translate("howToUse", "• Separate reactants from products using an arrow \'->\'"))
        self.label_bullet6.setText(_translate("howToUse", "• Press Balance button and check for its balanced equation."))
        self.groupBox_keyboardShortcut.setTitle(_translate("howToUse", "Keyboard Shortcuts"))
        self.label_bullet7.setText(_translate("howToUse", "• Ctrl + C to copy highlighted text."))
        self.label_bullet9.setText(_translate("howToUse", "• Ctrl + Q to close program."))
        self.label_bullet8.setText(_translate("howToUse", "• Ctrl + A to clear input."))
import assets_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    howToUse = QtWidgets.QMainWindow()
    ui = Ui_howToUse()
    ui.setupUi(howToUse)
    howToUse.show()
    sys.exit(app.exec_())
